name: build-checks-debian

on: [pull_request, push]

jobs:
  build-debian:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup STE
        run: bash install_debian.sh